codecov:
  require_ci_to_pass: false

ai_pr_review:
  enabled: true

comment:
  show_carryforward_flags: true

flags:
  cli:
    paths:
      - src/cli/**
    carryforward: true
  connection:
    paths:
      - src/connection/**
    carryforward: true
  database:
    paths:
      - src/database/**
    carryforward: true
  gateway:
    paths:
      - src/gateway/**
    carryforward: true
  mcots:
    paths:
      - src/mcots/**
    carryforward: true
  nps:
    paths:
      - src/nps/**
    carryforward: true
  patch:
    paths:
      - src/patch/**
    carryforward: true
  shard:
    paths:
      - src/shard/**
    carryforward: true
  shared:
    paths:
      - src/shared/**
    carryforward: true
  shared-packets:
    paths:
      - src/shared-packets/**
    carryforward: true
  schema:
    paths:
      - schema/**
    carryforward: true

component_management:
  individual_components:
    - component_id: components_nps
      name: NPS
      paths:
        - src/cli/**
        - src/connection/**
        - src/database/**
        - src/gateway/**
        - src/lobby/**
        - src/login/**
        - src/nps/**
        - src/patch/**
        - src/persona/**
        - src/shard/**
        - src/shared-packets/**
    - component_id: components_mcots
      name: MCOTS
      paths:
        - src/cli/**
        - src/connection/**
        - src/database/**
        - src/gateway/**
        - src/mcots/**
        - src/shared-packets/**
