codecov:
    require_ci_to_pass: false
comment:
  layout: "files,flags"
  behavior: "default"

flags:
  auth:
    paths:
      - packages/mcos-auth/**
    carryforward: false
  database:
    paths:
      - packages/mcos-database/**
    carryforward: false
  gateway:
    paths:
      - packages/mcos-gateway/**
    carryforward: false
  lobby:
    paths:
      - packages/mcos-lobby/**
    carryforward: false
  login:
    paths:
      - packages/mcos-login/**
    carryforward: false
  patch:
    paths:
      - packages/mcos-patch/**
    carryforward: false
  persona:
    paths:
      - packages/mcos-persona/**
    carryforward: false
  shard:
    paths:
      - packages/mcos-shard/**
    carryforward: false
  shared:
    paths:
      - src/shared/**
    carryforward: false
  transactions:
    paths:
      - packages/mcos-transactions/**
    carryforward: true


