comment:
  layout: "files,flags"
  behavior: "default"

flags:
  auth:
    paths:
      - packages/mcos-auth/**
    carryforward: true
  database:
    paths:
      - packages/mcos-database/**
    carryforward: true
  gateway:
    paths:
      - packages/mcos-gateway/**
    carryforward: true
  lobby:
    paths:
      - packages/mcos-lobby/**
    carryforward: true
  login:
    paths:
      - packages/mcos-login/**
    carryforward: true
  patch:
    paths:
      - packages/mcos-patch/**
    carryforward: true
  persona:
    paths:
      - packages/mcos-persona/**
    carryforward: true
  shard:
    paths:
      - packages/mcos-shard/**
    carryforward: true
  logger:
    paths:
      - packages/mcos-logger/**
    carryforward: false
  shared-structures:
    paths:
      - packages/mcos-shared/src/structures**
    carryforward: false
  shared-types:
    paths:
      - packages/mcos-shared/src/types/**
    carryforward: false
  shared:
    paths:
      - packages/mcos-shared/**
    carryforward: false
  transactions:
    paths:
      - packages/mcos-transactions/**
    carryforward: true


