codecov:
    require_ci_to_pass: false

flags:
  auth:
    paths:
      - packages/auth/**
    carryforward: true
  database:
    paths:
      - packages/database/**
    carryforward: true
  gateway:
    paths:
      - packages/gateway/**
    carryforward: true
  lobby:
    paths:
      - packages/lobby/**
    carryforward: true
  login:
    paths:
      - packages/login/**
    carryforward: true
  patch:
    paths:
      - packages/patch/**
    carryforward: true
  persona:
    paths:
      - packages/persona/**
    carryforward: true
  shard:
    paths:
      - packages/shard/**
    carryforward: true
  shared:
    paths:
      - packages/shared/**
    carryforward: true
  transactions:
    paths:
      - packages/transactions/**
    carryforward: true
  interfaces:
    paths:
      - packages/interfaces/**
    carryforward: true
  core:
    paths:
      - packages/core/**
    carryforward: true


