codecov:
    require_ci_to_pass: false

ai_pr_review:
    enabled: true

comment:
    show_carryforward_flags: true

flags:
    database:
        paths:
            - libs/database/**
        carryforward: true
    gateway:
        paths:
            - libs/gateway/**
        carryforward: true
    lobby:
        paths:
            - libs/lobby/**
        carryforward: true
    login:
        paths:
            - libs/login/**
        carryforward: true
    patch:
        paths:
            - libs/patch/**
        carryforward: true
    persona:
        paths:
            - libs/persona/**
        carryforward: true
    shard:
        paths:
            - libs/shard/**
        carryforward: true
    shared:
        paths:
            - libs/shared/**
        carryforward: true
    transactions:
        paths:
            - libs/transactions/**
        carryforward: true
    interfaces:
        paths:
            - libs/interfaces/**
        carryforward: false
    core:
        paths:
            - libs/core/**
        carryforward: true

component_management:
    individual_components:
        - component_id: components_team1
          name: Team 1
          paths:
              - libs/core/**
              - libs/gateway/**
              - libs/shared/**
