codecov:
    require_ci_to_pass: false

comment:
    show_carryforward_flags: true

flags:
    database:
        paths:
            - thebeast/packages/database/**
        carryforward: true
    gateway:
        paths:
            - thebeast/packages/gateway/**
        carryforward: true
    lobby:
        paths:
            - thebeast/packages/lobby/**
        carryforward: true
    login:
        paths:
            - thebeast/packages/login/**
        carryforward: true
    patch:
        paths:
            - thebeast/packages/patch/**
        carryforward: true
    persona:
        paths:
            - thebeast/packages/persona/**
        carryforward: true
    shard:
        paths:
            - thebeast/packages/shard/**
        carryforward: true
    shared:
        paths:
            - thebeast/packages/shared/**
        carryforward: true
    transactions:
        paths:
            - thebeast/packages/transactions/**
        carryforward: true
    interfaces:
        paths:
            - thebeast/packages/interfaces/**
        carryforward: false
    core:
        paths:
            - thebeast/packages/core/**
        carryforward: true

component_management:
    individual_components:
        - component_id: components_team1
          name: Team 1
          paths:
              - thebeast/packages/core/**
              - thebeast/packages/gateway/**
              - thebeast/packages/shared/**

coverage:
    status:
        project:
            default:
                removed_code_behavior: adjust_base
