# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: name-tests-test
- repo: https://github.com/pycqa/flake8
  rev: '7.1.0'  # pick a git hash / tag to point to
  hooks:
  -   id: flake8
      additional_dependencies: ['flake8-black']
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/pdm-project/pdm
  rev: 2.15.4 # a PDM release exposing the hook
  hooks:
  - id: pdm-export
  # command arguments, e.g.:
    args: ['-o', 'requirements.txt', '--without-hashes']
    files: ^pdm.lock$
  - id: pdm-lock-check
