version: "3.1"

services:
    nginx:
        build:
            context: services/sslProxy
        ports:
            - "443:443"
            - "80:80"
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
    db:
        image: postgres:16.3@sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c
        restart: always
        environment:
            POSTGRES_DB: rm
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        security_opt:
            - no-new-privileges:true

    adminer:
        image: adminer:4.8.1@sha256:ee90fd19757e0f89bb991f63bf04fd0530a0f98f408605d2b88f812fc0c3ec7b
        restart: always
        ports:
            - 8080:8080
        security_opt:
            - no-new-privileges:true

volumes:
    db-data:
        driver: local
