version: "3.1"

services:
  nginx:
    build:
      context: services/sslProxy
    ports:
      - "443:443"
    depends_on:
      - node

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  node:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=example
    volumes:
      - ./:/home/node/app
    expose:
      - "80:80"
    depends_on:
      - db
