version: "3.1"

services:
    nginx:
        build:
            context: services/sslProxy
        ports:
            - "443:443"
            - "80:80"
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
    db:
        image: postgres:16.3@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881
        restart: always
        environment:
            POSTGRES_DB: rm
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        security_opt:
            - no-new-privileges:true

    adminer:
        image: adminer:4.8.1@sha256:1cdc0bfddc5196e9fde4c2f9581a55e5e8fb3f063af4dc60ceb46ce4248c1ff3
        restart: always
        ports:
            - 8080:8080
        security_opt:
            - no-new-privileges:true

volumes:
    db-data:
        driver: local
