version: '3.4'

services:
  # mcoserver:
  #   image: mcoserver
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 80
  #     - 443
  #   labels:
  #     - "traefik.http.routers.bin.rule=Host(`bin.docker.localhost`)"
  patch:
    image: patch
    build:
      context: .
      dockerfile: Dockerfile.patch
    environment:
      NODE_ENV: production
      LISTEN_PORT: 4242
      LOG_LEVEL: silly
    ports:
      - "4242"      
    labels:
      - "traefik.http.patch.bin.rule=Host(`patch.docker.localhost`)" 
    depends_on:
      - router
  router:
    image: router
    build:
      context: ./packages/router
      dockerfile: Dockerfile.router
    environment:
      NODE_ENV: production
      LISTEN_PORT: 4242
      LOG_LEVEL: silly
    ports:
      - "4242"
    labels:
      - "traefik.http.router.bin.rule=Host(`router.docker.localhost`)"      
  database:
    image: database
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      NODE_ENV: production
      LOG_LEVEL: silly
    ports:
      - "80"
      - "443"
    labels:
      - "traefik.http.database.bin.rule=Host(`database.docker.localhost`)"  
    depends_on:
      - router          
  reverse-proxy:
      # The official v2 Traefik docker image
      image: traefik:v2.5
      # Enables the web UI and tells Traefik to listen to docker
      command: --api.insecure=true --providers.docker
      ports:
        # The HTTP port
        - "80:80"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"
      volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:14.0
    ports: 
      - "5432"
      # TODO: remove before prod https://github.com/drazisil/mco-server/issues/1008
    environment: 
      - "POSTGRES_PASSWORD=password"       
  pgadmin:
      image: dpage/pgadmin4:6.1
      # TODO: remove these before prod https://github.com/drazisil/mco-server/issues/1008
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
          PGADMIN_DEFAULT_PASSWORD: password
          PGADMIN_LISTEN_PORT: 80
      ports:
          - "15432:80"
      volumes:
          - pgadmin:/var/lib/pgadmin
      depends_on:
          - db
volumes:
  pgadmin: