version: "3.1"

services:
  nginx:
    build:
      context: services/sslProxy
    ports:
      - "443:443"
    depends_on:
      - node

  db:
    image: postgres:14.2
    ports:
      - "5432"
      # TODO: remove before prod https://github.com/drazisil/mco-server/issues/1008
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=mcos"
  pgadmin:
    image: dpage/pgadmin4:6.8
    # TODO: remove these before prod https://github.com/drazisil/mco-server/issues/1008
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  node:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - ENV NODE_ENV=production
      - ENV PGHOST=db
      - ENV PGUSER=postgres
      - ENV PGDATABASE=postgres
      - ENV PGPASSWORD=example=value
    volumes:
      - ./:/home/node/app
    command: "npm start"
    ports:
      - "80:80"
      - "6660:6660"
      - "8228:8228"
      - "8226:8226"
      - "7003:7003"
      - "8227:8227"
      - "43200:43200"
      - "43300:43300"
      - "43400:43400"
      - "53303:53303"
      - "9000-9014:9000-9014"
    depends_on:
      - db

volumes:
  pgadmin:
