name: Sentry Release

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    release-sentry:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
              with:
                  fetch-depth: 0

            - name: Enable Corepack
              run: |
                  corepack enable pnpm
            - name: Install and test using pnpm
              run: |
                  pnpm install
                  pnpm test

            - name: Create Sentry release
              uses: getsentry/action-release@586b62368d564f25d694ce05fcb9cf53de65ac4f # v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
                  # SENTRY_URL: https://sentry.io/
              with:
                  environment: production
