name: Sentry Release

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    release-sentry:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
              with:
                  fetch-depth: 0

            - name: Install and test using npm
              run: |
                  npm install
                  npm run test --workspaces --if-present

            - name: Create Sentry release
              uses: getsentry/action-release@586b62368d564f25d694ce05fcb9cf53de65ac4f # v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
                  # SENTRY_URL: https://sentry.io/
              with:
                  environment: production
