name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MCO_LOG_LEVEL: warn

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci install
      - name: Test
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npm test
      - name: Codecov
        env: # Or as an environment variable
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pip install --user codecov-cli
          codecovcli create-commit
          codecovcli create-report
          codecovcli do-upload -F auth
          codecovcli do-upload -F database
          codecovcli do-upload -F gateway
          codecovcli do-upload -F lobby
          codecovcli do-upload -F login
          codecovcli do-upload -F patch
          codecovcli do-upload -F persona
          codecovcli do-upload -F shard
          codecovcli do-upload -F transactions
                    
      - uses: actions/upload-artifact@v3
        with:
          name: coverage_${{ matrix.node-version }}
          path: coverage
