name: The Beast

on:
    push:
    pull_request:

env:
    MCO_LOG_LEVEL: warn
    EXTERNAL_HOST: mcouniverse.com
    PRIVATE_KEY_FILE: thebeast/data/private_key.pem
    CERTIFICATE_FILE: thebeast/data/mcouniverse.crt
    PUBLIC_KEY_FILE: thebeast/data/pub.key

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 21.x]

        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
              with:
                  fetch-depth: 0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
              with:
                  node-version: ${{ matrix.node-version }}
            # - name: Resolve Outdated Comments
            #   uses: Ardiannn08/resolve-outdated-comment@v1.3
            #   with:
            #       token: ${{ secrets.GH_TOKEN }}
            #       mode: "delete"
            - name: Install and test
              run: |
                  corepack enable pnpm
                  pnpm install
                  pnpm build
                  npm test
              env:
                  CODECOV_UPLOAD_BUNDLE_TOKEN: ${{ secrets.CODECOV_UPLOAD_BUNDLE_TOKEN }}
            - name: Codecov
              if: ${{ always() }}
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: |
                  pip install --user pytest
                  pip install --user codecov-cli
                  codecovcli --verbose create-commit --fail-on-error 
                  codecovcli --verbose create-report --fail-on-error 
                  codecovcli do-upload --report-type test_results --file mcos.junit.xml
                  codecovcli --verbose do-upload --fail-on-error --flag cli --name cli-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag connection --name connection-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag core --name core-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag database --name database-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag gateway --name gateway-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag lobby --name lobby-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag login --name login-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag mcots --name mcots-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag nps --name nps-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag patch --name patch-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag persona --name persona-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag shard --name shard-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag shared --name shared-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag shared-packets --name shared-packets-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag transactions --name transactions-${{ matrix.node-version }}

            - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
              with:
                  name: coverage_${{ matrix.node-version }}
                  path: coverage
