name: The Beast

on:
    push:
    pull_request:

env:
    MCO_LOG_LEVEL: warn

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x, 21.x]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Enable Corepack and set version to stable
              run: |
                  corepack enable
                  corepack set-version stable
            - name: Install and test thebeast workspace
              run: |
                  yarn workspace @rusty-motors/thebeast install
                  yarn workspace @rusty-motors/thebeast test
            - name: Codecov
              env: 
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
              run: |
                  pip install --user pytest
                  pip install --user codecov-cli
                  codecovcli --verbose create-commit --fail-on-error 
                  codecovcli --verbose create-report --fail-on-error 
                  codecovcli --verbose do-upload --fail-on-error --flag database --name database-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag gateway --name gateway-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag lobby --name lobby-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag login --name login-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag patch --name patch-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag persona --name persona-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag shard --name shard-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag transactions --name transactions-${{ matrix.node-version }}
                  codecovcli --verbose do-upload --fail-on-error --flag core --name core-${{ matrix.node-version }}

            - uses: actions/upload-artifact@v4
              with:
                  name: coverage_${{ matrix.node-version }}
                  path: coverage
