name: Semgrep
on:
    pull_request: {}
    push:
        branches:
            - main
            - master
        paths:
            - .github/workflows/semgrep.yml
    schedule:
        - cron: "0 0 * * 0"
jobs:
    semgrep:
        name: Scan
        runs-on: ubuntu-22.04
        env:
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        container:
            image: returntocorp/semgrep@sha256:470852e0f80a04389afd851de9809be8e8d2287ecc709abbc7834890786323fa
        if: (github.actor != 'dependabot[bot]')
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
            - run: semgrep ci
